#!/bin/bash
# Quick Start: Interview Scheduling Implementation
# This script guides you through setting up the new scheduling system

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Interview Scheduling - Implementation Quick Start             ║"
echo "╚════════════════════════════════════════════════════════════════╝"

echo ""
echo "📋 STEP 1: Database Migration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Run the SQL migration in Supabase SQL Editor:"
echo ""
echo "   1. Go to: https://app.supabase.com → Your Project → SQL Editor"
echo "   2. Create new query"
echo "   3. Copy & paste contents of:"
echo "      backend/migrations/add_notifications_and_invites.sql"
echo "   4. Click 'Run'"
echo ""
echo "   This creates:"
echo "   • interview_invites table"
echo "   • notifications table"
echo "   • RLS policies"
echo "   • Performance indexes"
echo ""
read -p "Press ENTER after running migration..."

echo ""
echo "✅ Verify in Supabase Table Editor:"
echo "   You should see new tables:"
echo "   • public.interview_invites"
echo "   • public.notifications"
echo ""

echo ""
echo "🚀 STEP 2: Backend - Verify API Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Start backend server:"
echo ""
echo "   cd backend"
echo "   python -m uvicorn app.main:app --reload"
echo ""
echo "✅ Navigate to API docs:"
echo ""
echo "   Open: http://localhost:8000/docs"
echo ""
echo "   You should see new endpoints:"
echo "   • POST   /api/v1/invites"
echo "   • GET    /api/v1/invites/{invite_id}"
echo "   • POST   /api/v1/invites/{invite_id}/respond"
echo "   • GET    /api/v1/notifications"
echo "   • POST   /api/v1/notifications/{id}/read"
echo "   • GET    /api/v1/recruiter/responses"
echo ""
read -p "Press ENTER after verifying endpoints..."

echo ""
echo "📚 STEP 3: Documentation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Read the following files:"
echo ""
echo "   📄 IMPLEMENTATION_SUMMARY.md"
echo "      → Overview of what was implemented"
echo ""
echo "   📄 API_SCHEDULING_CONTRACT.md"
echo "      → Complete API documentation"
echo "      → Request/response examples"
echo "      → Error handling"
echo ""
echo "   📄 FRONTEND_INTEGRATION_GUIDE.md"
echo "      → Step-by-step frontend integration"
echo "      → Code examples"
echo "      → Hook samples"
echo ""

echo ""
echo "🎯 STEP 4: Frontend Integration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Follow FRONTEND_INTEGRATION_GUIDE.md:"
echo ""
echo "   1. Fetch notifications in candidate dashboard"
echo "   2. When user clicks notification:"
echo "      → Extract invite_id from metadata"
echo "      → Call GET /api/v1/invites/{invite_id}"
echo "      → Display time slots"
echo ""
echo "   3. When user selects slot:"
echo "      → Call POST /api/v1/invites/{invite_id}/respond"
echo "      → Close modal on success"
echo ""
echo "   4. Recruiter dashboard:"
echo "      → Call GET /api/v1/recruiter/responses"
echo "      → Display responses section"
echo ""

echo ""
echo "🧪 STEP 5: Testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Test with curl (need valid auth tokens):"
echo ""
echo "   # Send invite (recruiter)"
echo "   curl -X POST http://localhost:8000/api/v1/invites \\"
echo "     -H 'Authorization: Bearer \$RECRUITER_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"application_id\":\"app-id\",\"proposed_time_slots\":[\"2026-03-28T09:00:00Z\"]}'"
echo ""
echo "   # Get notifications (candidate)"
echo "   curl http://localhost:8000/api/v1/notifications \\"
echo "     -H 'Authorization: Bearer \$CANDIDATE_TOKEN'"
echo ""
echo "   # Respond to invite (candidate)"
echo "   curl -X POST http://localhost:8000/api/v1/invites/inv-id/respond \\"
echo "     -H 'Authorization: Bearer \$CANDIDATE_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"selected_time_slot\":\"2026-03-28T09:00:00Z\"}'"
echo ""
echo "   # Get responses (recruiter)"
echo "   curl http://localhost:8000/api/v1/recruiter/responses \\"
echo "     -H 'Authorization: Bearer \$RECRUITER_TOKEN'"
echo ""

echo ""
echo "✨ STEP 6: Key Files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Backend Implementation:"
echo ""
echo "   📄 backend/app/api/endpoints/notifications.py"
echo "      → All new endpoints with full logging"
echo ""
echo "   📄 backend/app/schemas/schemas.py"
echo "      → Pydantic models for validation"
echo ""
echo "   📄 backend/app/main.py"
echo "      → Registered notifications router"
echo ""
echo "   📄 backend/app/api/endpoints/schedule.py"
echo "      → Enhanced with logging"
echo ""
echo "✅ Database:"
echo ""
echo "   📄 supabase_schema.sql"
echo "      → Updated with new tables"
echo ""
echo "   📄 backend/migrations/add_notifications_and_invites.sql"
echo "      → Migration script with RLS policies"
echo ""

echo ""
echo "✅ Documentation:"
echo ""
echo "   📄 IMPLEMENTATION_SUMMARY.md"
echo "   📄 API_SCHEDULING_CONTRACT.md"
echo "   📄 FRONTEND_INTEGRATION_GUIDE.md"
echo ""

echo ""
echo "📊 Flow Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1️⃣  Recruiter sends invite"
echo "       ↓ Calls: POST /api/v1/invites"
echo "       ↓ Backend creates interview_invites + notification"
echo ""
echo "   2️⃣  Candidate sees notification"
echo "       ↓ Frontend: GET /api/v1/notifications"
echo "       ↓ Extract invite_id from metadata"
echo ""
echo "   3️⃣  Candidate clicks notification"
echo "       ↓ Frontend: GET /api/v1/invites/{invite_id}"
echo "       ↓ Shows time slots in scheduling modal"
echo ""
echo "   4️⃣  Candidate selects slot"
echo "       ↓ Frontend: POST /api/v1/invites/{invite_id}/respond"
echo "       ↓ Backend updates status, notifies recruiter"
echo ""
echo "   5️⃣  Recruiter sees response"
echo "       ↓ Frontend: GET /api/v1/recruiter/responses"
echo "       ↓ Shows \"John Doe - Accepted March 28, 2:00 PM\""
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ✅ All Set! Begin with STEP 1 (Database Migration)             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
